site = "Mio sito"
Volt = "/dev/shm/metern1.txt"
met_V = "1_1"
smtp_S = "smtp.gmail.com"
smtp_P = 587
from_addr = "myaccount@email.com"
pwd = "pwd_My_email_account"
to_addrs = "email1@email.com,email2@email.com"
BlackOut = 1
LowV = 215
HiV = 245
lapse = 30
