site = "Prova sito nuovo"
Volt = "/home/pi/Filediprova/metern2.txt"
met_V = "2_1"
smtp_S = "smtp.gmail.com"
smtp_P = 587
from_addr = "cane.di.terranova@gmail.com"
pwd = "Amorospo76"
to_addrs = "amorospo@yahoo.it"
BlackOut = 1
LowV = 215
HiV = 245
lapse = 20
